// CLIENT
export const CLIENT_SET_USER = "CLIENT/SET_USER";
export const CLIENT_SET_ROLES = "CLIENT/SET_ROLES";
export const CLIENT_SET_THEME = "CLIENT/SET_THEME";
export const CLIENT_SET_LANGUAGE = "CLIENT/SET_LANGUAGE";

// PRODUCT
export const PRODUCT_SET_CATEGORIES = "PRODUCT/SET_CATEGORIES";
export const PRODUCT_SET_LIST = "PRODUCT/SET_LIST";
export const PRODUCT_SET_TOTAL = "PRODUCT/SET_TOTAL";
export const PRODUCT_SET_FETCH_STATE = "PRODUCT/SET_FETCH_STATE";
export const PRODUCT_SET_LIMIT = "PRODUCT/SET_LIMIT";
export const PRODUCT_SET_OFFSET = "PRODUCT/SET_OFFSET";
export const PRODUCT_SET_FILTER = "PRODUCT/SET_FILTER";
export const PRODUCT_SET_DETAIL = "PRODUCT_SET_DETAIL";
export const PRODUCT_SET_DETAIL_FETCH_STATE = "PRODUCT_SET_DETAIL_FETCH_STATE";

// SHOPPING CART
export const CART_SET_CART = "CART/SET_CART";
export const CART_SET_PAYMENT = "CART/SET_PAYMENT";
export const CART_SET_ADDRESS = "CART/SET_ADDRESS";

